import { useEffect, useState } from 'react';
import { ErrorMessage, Empty, Field, Loading, Notice, Page } from './shared';

type FieldConfig = { key: string; label: string; type?: string; required?: boolean };
type Props = { title: string; api: any; idKey: string; fields: FieldConfig[]; columns: string[]; format?: (item: any, key: string) => string };

export default function AdminCrud({ title, api, idKey, fields, columns, format }: Props) {
  const blank = Object.fromEntries(fields.map((field) => [field.key, '']));
  const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState<any>(blank); const [editing, setEditing] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const response = await api.getAll(); setItems(response.data.data || []); setError(''); } catch (err) { setError(ErrorMessage(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const payload = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value === '' ? undefined : ['rating','price','price_per_night','duration','destination_id'].includes(key) ? Number(value) : value])); if (editing) await api.update(editing, payload); else await api.create(payload); setForm(blank); setEditing(null); await load(); } catch (err) { setError(ErrorMessage(err)); } };
  const edit = (item: any) => { setEditing(item[idKey]); setForm(Object.fromEntries(fields.map((field) => [field.key, item[field.key] ?? '']))); };
  const remove = async (id: number) => { if (!window.confirm('Delete this record?')) return; try { await api.delete(id); await load(); } catch (err) { setError(ErrorMessage(err)); } };
  return <Page title={title}><div className="grid lg:grid-cols-[minmax(280px,360px)_1fr] gap-8"><form className="card p-6 space-y-4 h-fit" onSubmit={submit}><h2 className="text-xl font-bold">{editing ? 'Edit record' : 'Add record'}</h2>{error && <Notice>{error}</Notice>}{fields.map((field) => <Field key={field.key} label={field.label}><input className="form-input" type={field.type || 'text'} value={form[field.key]} onChange={(e) => setForm({ ...form, [field.key]: e.target.value })} required={field.required} /></Field>)}<div className="flex gap-2"><button className="btn-primary">{editing ? 'Update' : 'Create'}</button>{editing && <button type="button" className="btn-secondary" onClick={() => { setEditing(null); setForm(blank); }}>Clear</button>}</div></form><div>{loading ? <Loading /> : items.length === 0 ? <Empty /> : <div className="overflow-x-auto bg-white border rounded-lg"><table className="w-full text-left"><thead className="bg-gray-50"><tr>{columns.map((column) => <th className="p-3 text-sm" key={column}>{column}</th>)}<th className="p-3">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-t" key={item[idKey]}>{columns.map((column) => <td className="p-3 text-sm" key={column}>{format ? format(item, column) : String(item[column] ?? '-')}</td>)}<td className="p-3 whitespace-nowrap"><button className="text-blue-600 mr-3" onClick={() => edit(item)}>Edit</button><button className="text-red-600" onClick={() => remove(item[idKey])}>Delete</button></td></tr>)}</tbody></table></div>}</div></div></Page>;
}
